apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api
  labels:
    app: iris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - name: iris-api
        image: us-central1-docker.pkg.dev/silicon-synapse-461513-v6/my-repo/iris-api:latest
        ports:
        - containerPort: 8200

---
apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  type: LoadBalancer
  selector:
    app: iris
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8200
